var months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var emails = [
	{ name: "Peter Pan", to: "peter@pan.de" },
	{ name: "Molly", to: "molly@yahoo.com" },
	{ name: "Forneria Marconi", to: "live@japan.jp" },
	{ name: "Master <em>Sync</em>", to: "205bw@samsung.com" },
	{ name: "Dr. <strong>Tech</strong> de Log", to: "g15@logitech.com" },
	{ name: "Don Corleone", to: "don@vegas.com" },
	{ name: "Mc Chick", to: "info@donalds.org" },
	{ name: "Donnie Darko", to: "dd@timeshift.info" },
	{ name: "Quake The Net", to: "webmaster@quakenet.org" },
	{ name: "Dr. Write", to: "write@writable.com" }
];
/*
var subjects = [
     { sub: "AAD", descr: "Architectural Administration and Management"},
     { sub: "ABS", descr: "Applied Biological Sciences"},
     { sub: "ACC", descr: "Accountancy"},
     { sub: "ACO", descr: "Applied Computing"},
     { sub: "ACT", descr: "Actuarial Sciences"},
     { sub: "ADE", descr: "Architectural Design and Technology Studios"},
     { sub: "AEC", descr: "American English and Culture Program"},
     { sub: "AEP", descr: "Applied Ethics and the Professions"},
     { sub: "AES", descr: "Aerospace Studies"},
     { sub: "AET", descr: "Aeronautical Engineering Technology"},
     { sub: "AFH", descr: "African and African American Studies Humanities"},
     { sub: "AFR", descr: "African and African American Studies"},
     { sub: "AFS", descr: "African & African American Studies Social Science"},
     { sub: "AGB", descr: "Agribusiness"},
     { sub: "AIS", descr: "American Indian Studies"},
     { sub: "ALA", descr: "Architecture and Landscape Architecture"},
     { sub: "ALD", descr: "Aging and Lifespan Development"},
     { sub: "ALT", descr: "Alternative Energy Technologies"},
     { sub: "AME", descr: "Arts, Media, and Engineering"},
     { sub: "AMS", descr: "American Studies"},
     { sub: "AMT", descr: "Aeronautical Management Technology"},
     { sub: "ANP", descr: "Environmental Analysis and Programming"},
     { sub: "APA", descr: "Asian Pacific American Studies"},
     { sub: "APH", descr: "Architectural Philosophy and History"},
     { sub: "APL", descr: "Applied Linguistics"},
     { sub: "APM", descr: "Applied Mathematics"},
     { sub: "ARA", descr: "Art Auxiliary"},
     { sub: "ARB", descr: "Arabic"},
     { sub: "ARD", descr: "Art"},
     { sub: "ARE", descr: "Art Education"},
     { sub: "ARH", descr: "Architectural Philosophy and History"},
     { sub: "ARP", descr: "Architecture Professional Studies"},
     { sub: "ARS", descr: "Art History"},
     { sub: "ART", descr: "Art"},
     { sub: "ASB", descr: "Anthropology (Social and Behavioral)"},
     { sub: "ASC", descr: "Applied Science Core"},
     { sub: "ASM", descr: "Anthropology (Science and Mathematics)"},
     { sub: "AST", descr: "Astronomy"},
     { sub: "ASU", descr: "ASU"},
     { sub: "ATC", descr: "Air Traffic Control"},
     { sub: "ATE", descr: "Architecture and Landscape Architecture"},
     { sub: "AVC", descr: "Architectural Communication"},
     { sub: "BCH", descr: "Biochemistry"},
     { sub: "BCS", descr: "Serbo-Croatian"},
     { sub: "BIO", descr: "Biology"},
     { sub: "BIS", descr: "Bachelor of Interdisciplinary Studies"},
     { sub: "BLE", descr: "Bilingual Education"},
     { sub: "BME", descr: "Bioengineering"},
     { sub: "BMI", descr: "Biomedical Informatics"},
     { sub: "BUA", descr: "Business Administration"},
     { sub: "BUE", descr: "Business Education"},
     { sub: "BUS", descr: "Business"},
     { sub: "CBS", descr: "Computational Biosciences"},
     { sub: "CCS", descr: "Chicana and Chicano Studies"},
     { sub: "CDE", descr: "Child Development"},
     { sub: "CED", descr: "Counselor Education"},
     { sub: "CEE", descr: "Civil and Environmental Engineering"},
     { sub: "CET", descr: "Computer Engineering Technology"},
     { sub: "CFA", descr: "Herberger College of the Arts"},
     { sub: "CHE", descr: "Chemical Engineering"},
     { sub: "CHI", descr: "Chinese"},
     { sub: "CHM", descr: "Chemistry"},
     { sub: "CHP", descr: "Community Health Practice"},
     { sub: "CIM", descr: "Concrete Industry Management"},
     { sub: "CIS", descr: "Computer Information Systems"},
     { sub: "CLS", descr: "Clinical Laboratory Sciences/Medical Technology"},
     { sub: "CMA", descr: "Communication"},
     { sub: "CMN", descr: "Communication Studies"},
     { sub: "CNE", descr: "Construction Engineering"},
     { sub: "COE", descr: "College of Education"},
     { sub: "COM", descr: "Communication"},
     { sub: "CON", descr: "Construction"},
     { sub: "CPI", descr: "Computing & Informatics"},
     { sub: "CPP", descr: "College of Public Programs"},
     { sub: "CPY", descr: "Counseling Psychology"},
     { sub: "CRD", descr: "Community Resources and Development"},
     { sub: "CRJ", descr: "Criminal Justice"},
     { sub: "CSE", descr: "Computer Science and Engineering"},
     { sub: "CSH", descr: "Chicana and Chicano Studies Humanities"},
     { sub: "CSS", descr: "Chicana and Chicano Studies Social Science"},
     { sub: "CST", descr: "Computing Studies"},
     { sub: "CTI", descr: "Technology & Innovation"},
     { sub: "DAH", descr: "Dance History"},
     { sub: "DAN", descr: "Dance"},
     { sub: "DBA", descr: "Doctor of Business Administration"},
     { sub: "DCE", descr: "Dance"},
     { sub: "DCI", descr: "Curriculum and Instruction"},
     { sub: "DNC", descr: "Dance"},
     { sub: "DNP", descr: "Doctor of Nursing Practice"},
     { sub: "DON", descr: "Doctor of Nursing"},
     { sub: "DSC", descr: "Design"},
     { sub: "EAC", descr: "Early Childhood East"},
     { sub: "EAD", descr: "Education Administration and Supervision"},
     { sub: "ECD", descr: "Early Childhood Education"},
     { sub: "ECN", descr: "Economics"},
     { sub: "ECS", descr: "Early Childhood Special Education"},
     { sub: "ECT", descr: "Early Childhood Teaching and Leadership"},
     { sub: "EDA", descr: "Education Administration and Supervision"},
     { sub: "EDC", descr: "Education East"},
     { sub: "EDP", descr: "Educational Psychology"},
     { sub: "EDS", descr: "Environmental Design"},
     { sub: "EDT", descr: "Educational Technology"},
     { sub: "EED", descr: "Elementary Education"},
     { sub: "EEE", descr: "Electrical Engineering"},
     { sub: "EET", descr: "Electronics Engineering Technology"},
     { sub: "EGR", descr: "Engineering"},
     { sub: "ELL", descr: "Engilsh as a Second Language"},
     { sub: "EMS", descr: "Executive Sustainability Leadership"},
     { sub: "ENG", descr: "English"},
     { sub: "ENH", descr: "English/Humanities"},
     { sub: "EPA", descr: "Education Policy Analysis"},
     { sub: "EPD", descr: "Environmental Design and Planning"},
     { sub: "ESS", descr: "Environmental Social Science "},
     { sub: "EST", descr: "Electronic Systems Technology"},
     { sub: "ETC", descr: "Engineering Technology Core"},
     { sub: "ETH", descr: "Ethnic Studies"},
     { sub: "ETM", descr: "Environmental Technology Management"},
     { sub: "EXW", descr: "Exercise and Wellness"},
     { sub: "FAM", descr: "Family and Human Development"},
     { sub: "FAS", descr: "Family Studies"},
     { sub: "FIN", descr: "Finance"},
     { sub: "FLA", descr: "Foreign Languages"},
     { sub: "FMP", descr: "Film and Media Production"},
     { sub: "FMS", descr: "Film and Media Studies"},
     { sub: "FOR", descr: "Forensics"},
     { sub: "FRE", descr: "French"},
     { sub: "FSA", descr: "Fire Service Administration"},
     { sub: "FSE", descr: "Fulton School of Engineering"},
     { sub: "FSM", descr: "Fire Service Management"},
     { sub: "GCU", descr: "Cultural Geography"},
     { sub: "GER", descr: "German"},
     { sub: "GIS", descr: "Geographic Information Science"},
     { sub: "GIT", descr: "Graphic Information Technology"},
     { sub: "GLB", descr: "Global Business"},
     { sub: "GLG", descr: "Geological Sciences"},
     { sub: "GPH", descr: "Physical Geography"},
     { sub: "GRA", descr: "Graphic Design"},
     { sub: "GRD", descr: "Graduate College"},
     { sub: "GRK", descr: "Ancient Greek"},
     { sub: "GRN", descr: "Gerontology"},
     { sub: "GTD", descr: "Global Technology and Development"},
     { sub: "HCD", descr: "Science of Health Care Delivery"},
     { sub: "HCR", descr: "Health Care Related"},
     { sub: "HEB", descr: "Hebrew"},
     { sub: "HED", descr: "Higher and Postsecondary Education"},
     { sub: "HES", descr: "Health Science"},
     { sub: "HHE", descr: "Healthcare and Healing Environments"},
     { sub: "HIN", descr: "Hindu Studies"},
     { sub: "HON", descr: "Honors"},
     { sub: "HPS", descr: "History and Philosophy of Science"},
     { sub: "HRC", descr: "Humanities, Arts and Cultural Studies"},
     { sub: "HSC", descr: "Health Sciences"},
     { sub: "HSD", descr: "Human and Social Dimensions Science and Technology"},
     { sub: "HSM", descr: "Health Sector Management"},
     { sub: "HST", descr: "History"},
     { sub: "HTY", descr: "History"},
     { sub: "HUD", descr: "Housing and Urban Development"},
     { sub: "HUM", descr: "Humanities"},
     { sub: "IAP", descr: "Interdisciplinary Arts and Performance"},
     { sub: "IAS", descr: "Integrative Studies"},
     { sub: "IBS", descr: "International Business Studies"},
     { sub: "ICO", descr: "Continued Enrollment (ineligible students)"},
     { sub: "IDN", descr: "Indonesian"},
     { sub: "IED", descr: "Indian Education"},
     { sub: "IEE", descr: "Industrial Engineering"},
     { sub: "IFT", descr: "Information Technology"},
     { sub: "IMD", descr: "Instructional Media"},
     { sub: "IND", descr: "Industrial Design"},
     { sub: "INT", descr: "Interior Design"},
     { sub: "IPO", descr: "International Programs Overseas"},
     { sub: "ITA", descr: "Italian"},
     { sub: "JAC", descr: "Joint Admission Continuous Enrollment"},
     { sub: "JHR", descr: "Social Justice and Human Rights"},
     { sub: "JMC", descr: "Journalism and Mass Communication"},
     { sub: "JPN", descr: "Japanese"},
     { sub: "JUS", descr: "Justice Studies"},
     { sub: "KIN", descr: "Kinesiology"},
     { sub: "KOR", descr: "Korean"},
     { sub: "LAA", descr: "Landscape Architectural Administration"},
     { sub: "LAP", descr: "Landscape Architecture Professional Studies"},
     { sub: "LAT", descr: "Latin"},
     { sub: "LAW", descr: "Law"},
     { sub: "LDE", descr: "Landscape Architectural Design&Technology Studies"},
     { sub: "LEM", descr: "Law Enforcement and Management"},
     { sub: "LES", descr: "Legal and Ethical Studies"},
     { sub: "LIA", descr: "Liberal Arts and Sciences"},
     { sub: "LIM", descr: "Leadership in International Management"},
     { sub: "LIN", descr: "Linguistics"},
     { sub: "LIS", descr: "Library Science"},
     { sub: "LNP", descr: "Landscape Analysis and Programming"},
     { sub: "LPH", descr: "Landscape Architectural Philosophy and History"},
     { sub: "LSC", descr: "Life Sciences"},
     { sub: "LTC", descr: "Landscape Architectural Technology"},
     { sub: "LTE", descr: "Learning and Teaching Excellence"},
     { sub: "LWU", descr: "Law (Undergraduate)"},
     { sub: "MAE", descr: "Mechanical and Aerospace Engineering"},
     { sub: "MAK", descr: "Macedonian"},
     { sub: "MAS", descr: "Masters of Arts in Interdisciplinary Studies"},
     { sub: "MAT", descr: "Mathematics"},
     { sub: "MBB", descr: "Molecular Biosciences/Biotechnology"},
     { sub: "MCB", descr: "Molecular and Cellular Biology"},
     { sub: "MCE", descr: "Multicultural Education"},
     { sub: "MCN", descr: "Mass Communication"},
     { sub: "MCO", descr: "Mass Communication"},
     { sub: "MDC", descr: "Music and Digital Culture"},
     { sub: "MDL", descr: "Medical Laboratory Sciences"},
     { sub: "MET", descr: "Mechanical & Manufacturing Engineering Technology"},
     { sub: "MGT", descr: "Management"},
     { sub: "MHI", descr: "Master of Healthcare Innovation"},
     { sub: "MHL", descr: "Music History/Literature"},
     { sub: "MIC", descr: "Microbiology"},
     { sub: "MIS", descr: "Military Science"},
     { sub: "MKT", descr: "Marketing"},
     { sub: "MLS", descr: "Master of Liberal Studies"},
     { sub: "MSC", descr: "Music"},
     { sub: "MSE", descr: "Materials Science and Engineering"},
     { sub: "MTC", descr: "Music Theory and Composition"},
     { sub: "MTE", descr: "Mathematics Education"},
     { sub: "MUE", descr: "Music Education"},
     { sub: "MUP", descr: "Music Performance"},
     { sub: "MUS", descr: "Music"},
     { sub: "NAN", descr: "Nanoscience"},
     { sub: "NLM", descr: "Nonprofit Leadership and Management"},
     { sub: "NOR", descr: "Norwegian"},
     { sub: "NPS", descr: "Natural and Physical Sciences"},
     { sub: "NTR", descr: "Nutrition"},
     { sub: "NUR", descr: "Nursing"},
     { sub: "OBS", descr: "Obesity Prevention and Management"},
     { sub: "OGL", descr: "Organizational Leadership"},
     { sub: "OMT", descr: "Operations Management Technology"},
     { sub: "OPM", descr: "Operations and Production Management"},
     { sub: "PAF", descr: "Public Affairs"},
     { sub: "PGM", descr: "Professional Golf Management"},
     { sub: "PGV", descr: "Public Policy and Government"},
     { sub: "PHI", descr: "Philosophy"},
     { sub: "PHL", descr: "Philosophy"},
     { sub: "PHS", descr: "Physical Sciences"},
     { sub: "PHY", descr: "Physics"},
     { sub: "PLA", descr: "Landscape Architecture"},
     { sub: "PLB", descr: "Plant Biology"},
     { sub: "PLC", descr: "Polish Languages and Culture"},
     { sub: "PLS", descr: "Political Science"},
     { sub: "POL", descr: "Political Science"},
     { sub: "POR", descr: "Portuguese"},
     { sub: "POS", descr: "Political Science"},
     { sub: "PPE", descr: "Physical Education East"},
     { sub: "PRM", descr: "Parks and Recreation Management"},
     { sub: "PSB", descr: "Psychology Behavior Analysis"},
     { sub: "PSY", descr: "Psychology (Science and Math)"},
     { sub: "PUB", descr: "Scholarly Publishing"},
     { sub: "PUP", descr: "Urban and Environmental Planning"},
     { sub: "QBA", descr: "Quantitative Business Analysis"},
     { sub: "RDG", descr: "Reading Education"},
     { sub: "REA", descr: "Real Estate"},
     { sub: "RED", descr: "Real Estate Development"},
     { sub: "REL", descr: "Religious Studies"},
     { sub: "ROM", descr: "Romanian"},
     { sub: "RTM", descr: "Recreation and Tourism Management"},
     { sub: "RUS", descr: "Russian"},
     { sub: "SBS", descr: "Social and Behavioral Sciences"},
     { sub: "SCA", descr: "Scandinavian"},
     { sub: "SCL", descr: "Sociology"},
     { sub: "SCM", descr: "Supply Chain Management"},
     { sub: "SCN", descr: "Science Education"},
     { sub: "SDE", descr: "Secondary Education East"},
     { sub: "SEC", descr: "Solar Energy Engineering & Commercialization"},
     { sub: "SED", descr: "Secondary Education"},
     { sub: "SEM", descr: "Science and Engineering of Materials"},
     { sub: "SER", descr: "Software Engineering"},
     { sub: "SES", descr: "Earth and Space Exploration"},
     { sub: "SET", descr: "Security Engineering Technology"},
     { sub: "SGS", descr: "School of Global Studies"},
     { sub: "SHS", descr: "Speech and Hearing Science"},
     { sub: "SLC", descr: "School of International Letters and Cultures"},
     { sub: "SLV", descr: "Slavic"},
     { sub: "SOC", descr: "Sociology"},
     { sub: "SOS", descr: "School of Sustainability"},
     { sub: "SPA", descr: "Spanish"},
     { sub: "SPC", descr: "Special Education East"},
     { sub: "SPE", descr: "Special Education"},
     { sub: "SPF", descr: "Social and Philosophical Foundations"},
     { sub: "SPN", descr: "Spanish"},
     { sub: "SSB", descr: "Social and Behavioral Sciences"},
     { sub: "SSH", descr: "Social Science and Health"},
     { sub: "STP", descr: "Statistics and Probability"},
     { sub: "STS", descr: "Science, Technology, and Society"},
     { sub: "SWE", descr: "Swedish"},
     { sub: "SWG", descr: "Social Work (Graduate)"},
     { sub: "SWU", descr: "Social Work (Undergraduate)"},
     { sub: "TCL", descr: "Transborder Chicana/o and Latina"},
     { sub: "TDM", descr: "Tourism Development and Management"},
     { sub: "TEL", descr: "Teacher Education and Leadership"},
     { sub: "THA", descr: "Thai"},
     { sub: "THE", descr: "Theatre"},
     { sub: "THF", descr: "School of Theatre and Film"},
     { sub: "THP", descr: "Theatre Performance and Production"},
     { sub: "THR", descr: "Theatre"},
     { sub: "TMC", descr: "Technology Management Core"},
     { sub: "TRC", descr: "Transportation Systems Certificate"},
     { sub: "TWC", descr: "Multimedia Writing and Technical Communication"},
     { sub: "UET", descr: "Microelectronics Engineering Technology"},
     { sub: "UNI", descr: "University"},
     { sub: "URB", descr: "Urban and Metropolitan Studies"},
     { sub: "VTN", descr: "Vietnamese"},
     { sub: "WAC", descr: "Writing Across the Curriculum"},
     { sub: "WNS", descr: "Women's Studies"},
     { sub: "WPC", descr: "W.P. Carey School of Business"},
     { sub: "WST", descr: "Women's Studies"}
];*/


var cities = [
	"Aberdeen", "Ada", "Adamsville", "Addyston", "Adelphi", "Adena", "Adrian", "Akron",
	"Albany", "Alexandria", "Alger", "Alledonia", "Alliance", "Alpha", "Alvada",
	"Alvordton", "Amanda", "Amelia", "Amesville", "Amherst", "Amlin", "Amsden",
	"Amsterdam", "Andover", "Anna", "Ansonia", "Antwerp", "Apple Creek", "Arcadia",
	"Arcanum", "Archbold", "Arlington", "Ashland", "Ashley", "Ashtabula", "Ashville",
	"Athens", "Attica", "Atwater", "Augusta", "Aurora", "Austinburg", "Ava", "Avon",
	"Avon Lake", "Bainbridge", "Bakersville", "Baltic", "Baltimore", "Bannock",
	"Barberton", "Barlow", "Barnesville", "Bartlett", "Barton", "Bascom", "Batavia",
	"Bath", "Bay Village", "Beach City", "Beachwood", "Beallsville", "Beaver",
	"Beaverdam", "Bedford", "Bellaire", "Bellbrook", "Belle Center", "Belle Valley",
	"Bellefontaine", "Bellevue", "Bellville", "Belmont", "Belmore", "Beloit", "Belpre",
	"Benton Ridge", "Bentonville", "Berea", "Bergholz", "Berkey", "Berlin",
	"Berlin Center", "Berlin Heights", "Bethel", "Bethesda", "Bettsville", "Beverly",
	"Bidwell", "Big Prairie", "Birmingham", "Blacklick", "Bladensburg", "Blaine",
	"Blakeslee", "Blanchester", "Blissfield", "Bloomdale", "Bloomingburg",
	"Bloomingdale", "Bloomville", "Blue Creek", "Blue Rock", "Bluffton",
	"Bolivar", "Botkins", "Bourneville", "Bowerston", "Bowersville",
	"Bowling Green", "Bradford", "Bradner", "Brady Lake", "Brecksville",
	"Bremen", "Brewster", "Brice", "Bridgeport", "Brilliant", "Brinkhaven",
	"Bristolville", "Broadview Heights", "Broadway", "Brookfield", "Brookpark",
	"Brookville", "Brownsville", "Brunswick", "Bryan", "Buchtel", "Buckeye Lake",
	"Buckland", "Bucyrus", "Buffalo", "Buford", "Burbank", "Burghill", "Burgoon",
	"Burkettsville", "Burton", "Butler", "Byesville", "Cable", "Cadiz", "Cairo",
	"Caldwell", "Caledonia", "Cambridge", "Camden", "Cameron", "Camp Dennison",
	"Campbell", "Canal Fulton", "Canal Winchester", "Canfield", "Canton", "Carbon Hill",
	"Carbondale", "Cardington", "Carey", "Carroll", "Carrollton", "Casstown",
	"Castalia", "Catawba", "Cecil", "Cedarville", "Celina", "Centerburg",
	"Chagrin Falls", "Chandlersville", "Chardon", "Charm", "Chatfield", "Chauncey",
	"Cherry Fork", "Chesapeake", "Cheshire", "Chester", "Chesterhill", "Chesterland",
	"Chesterville", "Chickasaw", "Chillicothe", "Chilo", "Chippewa Lake",
	"Christiansburg", "Cincinnati", "Circleville", "Clarington", "Clarksburg",
	"Clarksville", "Clay Center", "Clayton", "Cleveland", "Cleves", "Clifton",
	"Clinton", "Cloverdale", "Clyde", "Coal Run", "Coalton", "Coldwater", "Colerain",
	"College Corner", "Collins", "Collinsville", "Colton", "Columbia Station",
	"Columbiana", "Columbus", "Columbus Grove", "Commercial Point", "Conesville",
	"Conneaut", "Conover", "Continental", "Convoy", "Coolville", "Corning", "Cortland",
	"Coshocton", "Covington", "Creola", "Crestline", "Creston", "Crooksville",
	"Croton", "Crown City", "Cuba", "Cumberland", "Curtice", "Custar", "Cutler",
	"Cuyahoga Falls", "Cygnet", "Cynthiana", "Dalton", "Damascus", "Danville",
	"Dayton", "De Graff", "Decatur", "Deerfield", "Deersville", "Defiance",
	"Delaware", "Dellroy", "Delphos", "Delta", "Dennison", "Derby", "Derwent",
	"Deshler", "Dexter City", "Diamond", "Dillonvale", "Dola", "Donnelsville",
	"Dorset", "Dover", "Doylestown", "Dresden", "Dublin", "Dunbridge", "Duncan Falls",
	"Dundee", "Dunkirk", "Dupont", "East Claridon", "East Fultonham",
	"East Liberty", "East Liverpool", "East Palestine", "East Rochester",
	"East Sparta", "East Springfield", "Eastlake", "Eaton", "Edgerton", "Edison",
	"Edon", "Eldorado", "Elgin", "Elkton", "Ellsworth", "Elmore", "Elyria",
	"Empire", "Englewood", "Enon", "Etna", "Euclid", "Evansport", "Fairborn",
	"Fairfield", "Fairpoint", "Fairview", "Farmdale", "Farmer", "Farmersville",
	"Fayette", "Fayetteville", "Feesburg", "Felicity", "Findlay", "Flat Rock",
	"Fleming", "Fletcher", "Flushing", "Forest", "Fort Jennings", "Fort Loramie",
	"Fort Recovery", "Fostoria", "Fowler", "Frankfort", "Franklin",
	"Franklin Furnace", "Frazeysburg", "Fredericksburg", "Fredericktown",
	"Freeport", "Fremont", "Fresno", "Friendship", "Fulton", "Fultonham",
	"Galena", "Galion", "Gallipolis", "Galloway", "Gambier", "Garrettsville",
	"Gates Mills", "Geneva", "Genoa", "Georgetown", "Germantown", "Gettysburg",
	"Gibsonburg", "Girard", "Glandorf", "Glencoe", "Glenford", "Glenmont",
	"Glouster", "Gnadenhutten", "Gomer", "Goshen", "Grafton", "Grand Rapids",
	"Grand River", "Granville", "Gratiot", "Gratis", "Graysville", "Graytown",
	"Green", "Green Camp", "Green Springs", "Greenfield", "Greenford",
	"Greentown", "Greenville", "Greenwich", "Grelton", "Grove City",
	"Groveport", "Grover Hill", "Guysville", "Gypsum", "Hallsville",
	"Hamden", "Hamersville", "Hamilton", "Hamler", "Hammondsville",
	"Hannibal", "Hanoverton", "Harbor View", "Harlem Springs", "Harpster",
	"Harrisburg", "Harrison", "Harrisville", "Harrod", "Hartford", "Hartville",
	"Harveysburg", "Haskins", "Haverhill", "Haviland", "Haydenville", "Hayesville",
	"Heath", "Hebron", "Helena", "Hicksville", "Higginsport", "Highland", "Hilliard",
	"Hillsboro", "Hinckley", "Hiram", "Hockingport", "Holgate", "Holland",
	"Hollansburg", "Holloway", "Holmesville", "Homer", "Homerville", "Homeworth",
	"Hooven", "Hopedale", "Hopewell", "Houston", "Howard", "Hoytville", "Hubbard",
	"Hudson", "Huntsburg", "Huntsville", "Huron", "Iberia", "Independence",
	"Irondale", "Ironton", "Irwin", "Isle Saint George", "Jackson", "Jackson Center",
	"Jacksontown", "Jacksonville", "Jacobsburg", "Jamestown", "Jasper",
	"Jefferson", "Jeffersonville", "Jenera", "Jeromesville", "Jerry City",
	"Jerusalem", "Jewell", "Jewett", "Johnstown", "Junction City", "Kalida",
	"Kansas", "Keene", "Kelleys Island", "Kensington", "Kent", "Kenton",
	"Kerr", "Kettlersville", "Kidron", "Kilbourne", "Killbuck", "Kimbolton",
	"Kings Mills", "Kingston", "Kingsville", "Kinsman", "Kipling", "Kipton",
	"Kirby", "Kirkersville", "Kitts Hill", "Kunkle", "La Rue", "Lacarne",
	"Lafayette", "Lafferty", "Lagrange", "Laings", "Lake Milton", "Lakemore",
	"Lakeside Marblehead", "Lakeview", "Lakeville", "Lakewood", "Lancaster",
	"Langsville", "Lansing", "Latham", "Latty", "Laura", "Laurelville",
	"Leavittsburg", "Lebanon", "Lees Creek", "Leesburg", "Leesville",
	"Leetonia", "Leipsic", "Lemoyne", "Lewis Center", "Lewisburg",
	"Lewistown", "Lewisville", "Liberty Center", "Lima", "Limaville",
	"Lindsey", "Lisbon", "Litchfield", "Lithopolis", "Little Hocking",
	"Lockbourne", "Lodi", "Logan", "London", "Londonderry",
	"Long Bottom", "Lorain", "Lore City", "Loudonville", "Louisville",
	"Loveland", "Lowell", "Lowellville", "Lower Salem", "Lucas",
	"Lucasville", "Luckey", "Ludlow Falls", "Lynchburg", "Lynx",
	"Lyons", "Macedonia", "Macksburg", "Madison", "Magnetic Springs",
	"Magnolia", "Maineville", "Malaga", "Malinta", "Malta", "Malvern",
	"Manchester", "Mansfield", "Mantua", "Maple Heights", "Maplewood",
	"Marathon", "Marengo", "Maria Stein", "Marietta", "Marion",
	"Mark Center", "Marshallville", "Martel", "Martin", "Martins Ferry",
	"Martinsburg", "Martinsville", "Marysville", "Mason", "Massillon",
	"Masury", "Maumee", "Maximo", "Maynard", "Mc Arthur", "Mc Clure",
	"Mc Comb", "Mc Connelsville", "Mc Cutchenville", "Mc Dermott",
	"Mc Donald", "Mc Guffey", "Mechanicsburg", "Mechanicstown",
	"Medina", "Medway", "Melmore", "Melrose", "Mendon", "Mentor",
	"Mesopotamia", "Metamora", "Miamisburg", "Miamitown", "Miamiville",
	"Middle Bass", "Middle Point", "Middlebranch", "Middleburg",
	"Middlefield", "Middleport", "Middletown", "Midland", "Midvale",
	"Milan", "Milford", "Milford Center", "Millbury", "Milledgeville",
	"Miller City", "Millersburg", "Millersport", "Millfield",
	"Milton Center", "Mineral City", "Mineral Ridge", "Minerva",
	"Minford", "Mingo", "Mingo Junction", "Minster", "Mogadore",
	"Monclova", "Monroe", "Monroeville", "Montezuma", "Montpelier",
	"Montville", "Morral", "Morristown", "Morrow", "Moscow",
	"Mount Blanchard", "Mount Cory", "Mount Eaton", "Mount Gilead",
	"Mount Hope", "Mount Liberty", "Mount Orab", "Mount Perry",
	"Mount Pleasant", "Mount Saint Joseph", "Mount Sterling",
	"Mount Vernon", "Mount Victory", "Mowrystown", "Moxahala",
	"Munroe Falls", "Murray City", "Nankin", "Napoleon", "Nashport",
	"Nashville", "Navarre", "Neapolis", "Neffs", "Negley",
	"Nelsonville", "Nevada", "Neville", "New Albany", "New Athens",
	"New Bavaria", "New Bloomington", "New Bremen", "New Carlisle",
	"New Concord", "New Hampshire", "New Haven", "New Holland",
	"New Knoxville", "New Lebanon", "New Lexington", "New London",
	"New Madison", "New Marshfield", "New Matamoras", "New Middletown",
	"New Paris", "New Philadelphia", "New Plymouth", "New Richmond",
	"New Riegel", "New Rumley", "New Springfield", "New Straitsville",
	"New Vienna", "New Washington", "New Waterford", "New Weston",
	"Newark", "Newbury", "Newcomerstown", "Newport", "Newton Falls",
	"Newtonsville", "Ney", "Niles", "North Baltimore", "North Bend",
	"North Benton", "North Bloomfield", "North Fairfield",
	"North Georgetown", "North Hampton", "North Jackson",
	"North Kingsville", "North Lawrence", "North Lewisburg",
	"North Lima", "North Olmsted", "North Ridgeville", "North Robinson",
	"North Royalton", "North Star", "Northfield", "Northwood", "Norwalk",
	"Norwich", "Nova", "Novelty", "Oak Harbor", "Oak Hill", "Oakwood",
	"Oberlin", "Oceola", "Ohio City", "Okeana", "Okolona", "Old Fort",
	"Old Washington", "Olmsted Falls", "Ontario", "Orangeville",
	"Oregon", "Oregonia", "Orient", "Orrville", "Orwell", "Osgood",
	"Ostrander", "Ottawa", "Ottoville", "Otway", "Overpeck",
	"Owensville", "Oxford", "Painesville", "Palestine", "Pandora",
	"Paris", "Parkman", "Pataskala", "Patriot", "Paulding", "Payne",
	"Pedro", "Peebles", "Pemberton", "Pemberville", "Peninsula",
	"Perry", "Perrysburg", "Perrysville", "Petersburg", "Pettisville",
	"Phillipsburg", "Philo", "Pickerington", "Piedmont", "Pierpont",
	"Piketon", "Piney Fork", "Pioneer", "Piqua", "Pitsburg",
	"Plain City", "Plainfield", "Pleasant City", "Pleasant Hill",
	"Pleasant Plain", "Pleasantville", "Plymouth", "Polk",
	"Pomeroy", "Port Clinton", "Port Jefferson", "Port Washington",
	"Port William", "Portage", "Portland", "Portsmouth", "Potsdam",
	"Powell", "Powhatan Point", "Proctorville", "Prospect", "Put in Bay",
	"Quaker City", "Quincy", "Racine", "Radnor", "Randolph", "Rarden",
	"Ravenna", "Rawson", "Ray", "Rayland", "Raymond", "Reedsville",
	"Reesville", "Reno", "Republic", "Reynoldsburg", "Richfield",
	"Richmond", "Richmond Dale", "Richwood", "Ridgeville Corners",
	"Ridgeway", "Rio Grande", "Ripley", "Risingsun", "Rittman",
	"Robertsville", "Rock Camp", "Rock Creek", "Rockbridge", "Rockford",
	"Rocky Ridge", "Rocky River", "Rogers", "Rome", "Rootstown", "Roseville",
	"Rosewood", "Ross", "Rossburg", "Rossford", "Roundhead", "Rudolph",
	"Rushsylvania", "Rushville", "Russells Point", "Russellville", "Russia",
	"Rutland", "Sabina", "Saint Clairsville", "Saint Henry", "Saint Johns",
	"Saint Louisville", "Saint Marys", "Saint Paris", "Salem", "Salesville",
	"Salineville", "Sandusky", "Sandyville", "Sarahsville", "Sardinia",
	"Sardis", "Savannah", "Scio", "Scioto Furnace", "Scott", "Scottown",
	"Seaman", "Sebring", "Sedalia", "Senecaville", "Seven Mile", "Seville",
	"Shade", "Shadyside", "Shandon", "Sharon Center", "Sharpsburg",
	"Shauck", "Shawnee", "Sheffield Lake", "Shelby", "Sherrodsville",
	"Sherwood", "Shiloh", "Short Creek", "Shreve", "Sidney", "Sinking Spring",
	"Smithfield", "Smithville", "Solon", "Somerdale", "Somerset",
	"Somerville", "South Bloomingville", "South Charleston", "South Lebanon",
	"South Point", "South Salem", "South Solon", "South Vienna",
	"South Webster", "Southington", "Sparta", "Spencer", "Spencerville",
	"Spring Valley", "Springboro", "Springfield", "Stafford", "Sterling",
	"Steubenville", "Stewart", "Stillwater", "Stockdale", "Stockport",
	"Stone Creek", "Stony Ridge", "Stout", "Stoutsville", "Stow", "Strasburg",
	"Stratton", "Streetsboro", "Strongsville", "Struthers", "Stryker",
	"Sugar Grove", "Sugarcreek", "Sullivan", "Sulphur Springs", "Summerfield",
	"Summit Station", "Summitville", "Sunbury", "Swanton", "Sycamore",
	"Sycamore Valley", "Sylvania", "Syracuse", "Tallmadge", "Tarlton",
	"Terrace Park", "The Plains", "Thompson", "Thornville", "Thurman",
	"Thurston", "Tiffin", "Tiltonsville", "Tipp City", "Tippecanoe", "Tiro",
	"Toledo", "Tontogany", "Torch", "Toronto", "Tremont City", "Trenton",
	"Trimble", "Trinway", "Troy", "Tuppers Plains", "Tuscarawas", "Twinsburg",
	"Uhrichsville", "Union City", "Union Furnace", "Unionport", "Uniontown",
	"Unionville", "Unionville Center", "Uniopolis", "Upper Sandusky", "Urbana",
	"Utica", "Valley City", "Van Buren", "Van Wert", "Vandalia", "Vanlue",
	"Vaughnsville", "Venedocia", "Vermilion", "Verona", "Versailles",
	"Vickery", "Vienna", "Vincent", "Vinton", "Wadsworth", "Wakefield",
	"Wakeman", "Walbridge", "Waldo", "Walhonding", "Walnut Creek", "Wapakoneta",
	"Warnock", "Warren", "Warsaw", "Washington Court House",
	"Washingtonville", "Waterford", "Waterloo", "Watertown", "Waterville",
	"Wauseon", "Waverly", "Wayland", "Wayne", "Waynesburg", "Waynesfield",
	"Waynesville", "Wellington", "Wellston", "Wellsville", "West Alexandria",
	"West Chester", "West Elkton", "West Farmington", "West Jefferson",
	"West Lafayette", "West Liberty", "West Manchester", "West Mansfield",
	"West Millgrove", "West Milton", "West Point", "West Portsmouth",
	"West Rushville", "West Salem", "West Union", "West Unity", "Westerville",
	"Westfield Center", "Westlake", "Weston", "Westville", "Wharton",
	"Wheelersburg", "Whipple", "White Cottage", "Whitehouse", "Wickliffe",
	"Wilberforce", "Wilkesville", "Willard", "Williamsburg", "Williamsfield",
	"Williamsport", "Williamstown", "Williston", "Willoughby", "Willow Wood",
	"Willshire", "Wilmington", "Wilmot", "Winchester", "Windham", "Windsor",
	"Winesburg", "Wingett Run", "Winona", "Wolf Run", "Woodsfield",
	"Woodstock", "Woodville", "Wooster", "Wren", "Xenia", "Yellow Springs",
	"Yorkshire", "Yorkville", "Youngstown", "Zaleski", "Zanesfield", "Zanesville",
	"Zoar"
];

